
psql --username "$POSTGRES_USER" << EOF
  CREATE DATABASE $KELRISKS_POSTGRES_DB;
  CREATE USER $KELRISKS_POSTGRES_USER WITH PASSWORD '$KELRISKS_POSTGRES_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $KELRISKS_POSTGRES_DB to $KELRISKS_POSTGRES_USER;
EOF

psql --username "$POSTGRES_USER" -d $KELRISKS_POSTGRES_DB << EOF
  CREATE EXTENSION postgis;
EOF

psql --username "$KELRISKS_POSTGRES_USER" -d $KELRISKS_POSTGRES_DB << EOF
  CREATE SCHEMA kelrisks;
  CREATE SCHEMA etl;
EOF


